### ISSUE TITLE
Reiniero-fpcup-bin

### ISSUE THREAD

**Issue by mariuszekpl** [LongDirtyAnimAlf/Reiniero-fpcup#10]
Always after commit you create new files in bin directory 
Changes in code is about <1000 chars but repository is bigger about 1MB 
Is possible create repo for bin files ? 

It's a small suggestion, not be heard ;)

**Comment by LongDirtyAnimAlf** [comment]
Thanks for the suggestion ... but ... I am a lazy guy ...
My current practise: build many modes and update repo, including binaries.
Please advice for an easy (lazy) way to update the binaries, then I will follow your path ... ;-)
