### ISSUE TITLE
missing ppcx64

### ISSUE THREAD

**Issue by mariuszekpl** [LongDirtyAnimAlf/Reiniero-fpcup#11]
My last correct build is from 2015-12-23
After build FPC I have 
fpc/bin/x86_64-linux/ppcx64
fpc/lib/fpc/3.1.1/ppcx64
(two identical files)

Today I have only one 
fpc/lib/fpc/3.1.1/ppcx64
and when try run fpc or fpc.sh I have 
**Error: ppcx64 can't be executed, error message: Failed to execute "ppcx64", error code: 127**
when  copy 
fpc/lib/fpc/3.1.1/ppcx64 to  fpc/lib/fpc/3.1.1/ppcx64
all works OK 

who create copy ppcx64 in fpc/bin/x86_64-linux directory ?
fpc install scripts or fpcup ?

**Comment by LongDirtyAnimAlf** [comment]
Confirmed !
And (hopefully) solved !!
Please test.

**Comment by mariuszekpl** [comment]
I tessted and result fail :(

`if (FNoJobs) then ProcessEx.Parameters.Add('--disablejobs') else`
this add "--disablejobs" to make parameters 


> fpclazup: info: Running make cycle for intermediate compiler:
> Executing : make "compiler_cycle" "--disablejobs" "FPC=/home/l1/lazarus/0201out/fpcbootstrap/ppcx64" "--directory=/home/l1/lazarus/0201out/fpc300bootstrap" "OVERRIDEVERSIONCHECK=1" (working dir: /home/l1/lazarus/0201out/fpc300bootstrap)
> make: unrecognized option '--disablejobs'
>

**Comment by LongDirtyAnimAlf** [comment]
Sorry about that ... please try again !

**Comment by mariuszmaximus** [comment]
I tessted and result : PASS !

**Comment by mariuszekpl** [comment]
I tessted and result PASS
