### ISSUE TITLE
include svn revision in build

### ISSUE THREAD

**Issue by Thaddy** [LongDirtyAnimAlf/Reiniero-fpcup#12]
In my own build scripts I always include the svn revision for trunk. Is this possible with fpcup?

I mean, I do this in my own batches:
REVINC=force REVSTR=33035 OPT="-dREVINC"

The revstr is actually dynamically build like this:
(warning fancy unreadable batch scripting!);
FOR /F "usebackq delims==M" %%i IN (`svnversion -n`) DO set REVSTR=%%i

I would love to see that feature in fpcup by default for trunk.

**Comment by LongDirtyAnimAlf** [comment]
There is an option to set the revision:
--fpcrevision="33035"
Did you try this option ?
And did it work ?

**Comment by mariuszekpl** [comment]
with option "--getfullrepo"  in lazarus  "Help->About lazarus" show svn revision
