### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by shobits1** [LongDirtyAnimAlf/Reiniero-fpcup#13]
I can't make lazarus trunk with fpc-rtti

[fpcup.log](https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/files/127318/fpcup.log.txt)
[mysettings.ini](https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/files/127322/mysettings.ini.txt)
[mysettings-fpcup-trunkall-verbose.bat](https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/files/127323/mysettings-fpcup-trunkall-verbose.bat.txt)
[mysettings-fpcup-trunklaz-verbose.bat](https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/files/127324/mysettings-fpcup-trunklaz-verbose.bat.txt)

**Comment by LongDirtyAnimAlf** [comment]
Confirmed !
And solved (latest update).
Thanks for reporting !
