### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by joeparkerz** [LongDirtyAnimAlf/Reiniero-fpcup#15]
fpclazup: info: Error running fpcup. Technical details: error executing sequence fpc; line: 5, param: FPC
fpclazup: info: Error running fpcup. Technical details: error executing sequence DefaultWin32; line: 3

C:\>fpclazup.exe --fpcURL=trunk --lazURL=trunk --installdir="C:\Development\"
Fpclazup, a FPC/Lazarus downloader/updater/installer
Original by BigChimp: https://bitbucket.org/reiniero/fpcup
This version: https://github.com/LongDirtyAnimAlf/Reiniero-fpcup

Fpclazup will download the FPC and Lazarus sources
from the source SVN repositories, and compile, and install.
Result: you get a fresh, up-to-date Lazarus/FPC installation.

Version: based on commit fpcup001 (20150210)
Build date: 2016/02/18 16:41:41
Compiled for CPU: i386 on win32

Options:
Binutils/make dir:  C:\Development\fpcbootstrap
Bootstrap dir:      C:\Development\fpcbootstrap
FPC URL:            http://svn.freepascal.org/svn/fpc/trunk/
FPC options:
FPC directory:      C:\Development\fpc
Lazarus URL:        http://svn.freepascal.org/svn/lazarus/trunk
Lazarus options:
Lazarus directory:  C:\Development\lazarus
Keep changes:       no
Re-apply changes:   no
Log file name:      fpcup.log
Standard modules:   suggestedpackages
Standard modules:   lhelp
Standard modules:   lazdatadesktop
Standard modules:   doceditor

INFO: FPCUP will not download repos. It will only get the files !!!

******************************************************************
 You are now installing a bleeding edge version of [FPC/Lazarus].
 Please be forewarned that things might not function,
 as you would expect from a stable release.
 Installing a stable release,
 will give you a stable development environment,
 and is the preferred way of using [FPC/Lazarus].

 PS: You can build Lazarus trunk with normal FPC stable !! <-----
     Just execute fpclazup --lazURL="trunk"                <-----
******************************************************************

Effective parameters:
--fpcURL=trunk
--lazURL=trunk
--installdir=C:\Development\
Persistent parameters (can be saved in batch file):
--installdir="C:\Development\" --fpcURL="trunk" --lazURL="trunk"
Continue (Y/n): y
fpclazup: info: 2/26/2016 10:46:32: fpcup fpcup001 (20150210) started.
fpclazup: info: C:\Development\fpcbootstrap\ppc386.exe is not a valid ppc386.exe application (ppc386.exe result code was: -1)
fpclazup: info: Make path C:\Development\fpcbootstrap does not exist. Going to download binutils.
fpclazup: info: Downloading: cpp.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\cpp.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/cpp.exe
fpclazup: info: Downloading: dlltool.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\dlltool.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/dlltool.exe
fpclazup: info: Downloading: fp32.ico into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\fp32.ico from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/fp32.ico
fpclazup: info: Downloading: gcc.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\gcc.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/gcc.exe
fpclazup: info: Downloading: grep.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\grep.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/grep.exe
fpclazup: info: Downloading: patch.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\patch.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/patch.exe
fpclazup: info: Downloading: patch.exe.manifest into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\patch.exe.manifest from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/patch.exe.manifest
fpclazup: info: Downloading: unzip.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\unzip.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/unzip.exe
fpclazup: info: Downloading: windres.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\windres.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/windres.exe
fpclazup: info: Downloading: windres.h into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\windres.h from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/windres.h
fpclazup: info: Downloading: zip.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\zip.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/zip.exe
fpclazup: info: Downloading: ar.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\ar.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/ar.exe
fpclazup: info: Downloading: as.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\as.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/as.exe
fpclazup: info: Downloading: cmp.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\cmp.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/cmp.exe
fpclazup: info: Downloading: cp.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\cp.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/cp.exe
fpclazup: info: Downloading: diff.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\diff.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/diff.exe
fpclazup: info: Downloading: gdate.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\gdate.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/gdate.exe
fpclazup: info: Downloading: gdb.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\gdb.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/gdb.exe
fpclazup: info: Downloading: libexpat-1.dll into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\libexpat-1.dll from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/libexpat-1.dll
fpclazup: info: Downloading: gecho.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\gecho.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/gecho.exe
fpclazup: info: Downloading: ginstall.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\ginstall.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/ginstall.exe
fpclazup: info: Downloading: ginstall.exe.manifest into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\ginstall.exe.manifest from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/ginstall.exe.manifest
fpclazup: info: Downloading: gmkdir.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\gmkdir.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/gmkdir.exe
fpclazup: info: Downloading: ld.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\ld.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/ld.exe
fpclazup: info: Downloading: make.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\make.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/make.exe
fpclazup: info: Downloading: mv.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\mv.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/mv.exe
fpclazup: info: Downloading: objdump.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\objdump.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/objdump.exe
fpclazup: info: Downloading: pwd.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\pwd.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/pwd.exe
fpclazup: info: Downloading: rm.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\rm.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/rm.exe
fpclazup: info: Downloading: strip.exe into C:\Development\fpcbootstrap
fpclazup: info: Going to download C:\Development\fpcbootstrap\strip.exe from URL: http://svn2.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/strip.exe
fpclazup: WARNING: No OpenSLL library files available. Going to download them
fpclazup: info: Going to download C:\Users\ADMINI~1\AppData\Local\Temp\TMP00000.tmp.zip from URL: http://indy.fulgan.com/SSL/openssl-1.0.2e-i386-win32.zip
fpclazup: info: OpenSLL download and unpacking ok.
fpclazup: WARNING: Could not find svn executable in or under C:\Development\fpcbootstrap\svn\
fpclazup: info: Going to download SVN
fpclazup: info: Going to download C:\Users\ADMINI~1\AppData\Local\Temp\TMP00000.tmp.zip from URL: https://www.visualsvn.com/files/Apache-Subversion-1.9.1.zip
fpclazup: info: SVN download and unpacking ok. Not going to search SVN client itself in C:\Development\fpcbootstrap\svn\
fpclazup: info: SVN client found: C:\Development\fpcbootstrap\svn\bin\svn.exe
fpclazup: info: Going to download C:\Users\ADMINI~1\AppData\Local\Temp\TMP00000.tmp from URL: ftp://ftp.freepascal.org/pub/fpc/dist/2.6.4/bootstrap/i386-win32-ppc386.zip
fpclazup: info: Going to rename/move C:\Users\ADMINI~1\AppData\Local\Temp\ppc386.exe to C:\Development\fpcbootstrap\ppc386.exe
fpclazup: WARNING: FPC: CleanModule: directory C:\Development\fpc does not exist. Exiting CleanModule.
fpclazup: info: Checking out/updating FPC sources...
fpclazup: info: INFO: directory C:\Development\fpc is not an SVN repository (or a repository with the wrong remote URL).
fpclazup: info: INFO: creating directory C:\Development\fpc for SVN checkout.
fpclazup: info: Running SVN checkout or update.
fpclazup: info: TFPCInstaller: building module FPC...
fpclazup: info: We have a FPC source (@ C:\Development\fpc) with version: 3.1.1
fpclazup: info: Checking out/updating FPC 3.0.0 sources for intermediate bootstrap compiler ...
fpclazup: info: Checking out/updating FPC 3.0.0 sources for intermediate bootstrap compiler done.
fpclazup: info: Running make cycle for intermediate compiler:
fpclazup: info: FPC: Failed to build intermediate bootstrap compiler
**fpclazup: info: Error running fpcup. Technical details: error executing sequence fpc; line: 5, param: FPC
fpclazup: info: Error running fpcup. Technical details: error executing sequence DefaultWin32; line: 3, **param: fpc
Fpclazup failed.
Please check log for details. Possible troubleshooting steps:
- run again with --verbose and check for make, lazbuild errors etc.
- if compiling Lazarus, make sure your lhelp is closed.
- try removing all intermediate files by running fpcup with the --clean option
  and/or manually deleting all *.ppu/*.a/*.o followed by svn up
- if that does not work: use the --uninstall option to remove all files
  including your FPC and Lazarus directories
- remove the files in the bootstrap directory. fpcup will redownload if required.
fpclazup: info: 2/26/2016 10:51:21: fpcup finished.

**Comment by LongDirtyAnimAlf** [comment]
Please report back if this problem is solved.
If so, this issue can be closed.
