### ISSUE TITLE
Patch/Patchcmd

### ISSUE THREAD

**Issue by martok** [LongDirtyAnimAlf/Reiniero-fpcup#16]
I would like to use `git apply` to apply mail-style patches in the build process (after a clean checkout from svn). However, the `patchcmd` option is currently ignored, and even if it wasn't, both TFPCInstaller and TLazarusInstaller pass a number of parameter specific to GNU patch, so that wouldn't work. According to --help, it was once intended differently...

**Comment by LongDirtyAnimAlf** [comment]
Mmmm ... I will look into it ...
I did not realise this use of patchcmd !

**Comment by LongDirtyAnimAlf** [comment]
@martok 
Would you mind testing the new version ?
Thanks.

**Comment by martok** [comment]
Hm, tested building lazarus trunk using `... "--patchcmd=git patch" --lazrevision=51873 "--lazpatch=0001-IDE-fix-Before-tool-execution-simplify-project-build.patch"` (this is my patch that was applied in 51874, so I know it applies cleanly ;) )

Am I missing something, or is the --patchcmd completely ignored now? The code now always calls patch(or gpatch) for SourcePatches... if it would do that at all. It doesn't do anything at all for me, nothing mentioning logs in the log files. ProcMon doesn't even show any file access, so it can't be the FileExists checks on installerlazarus.pas:1093f either...

**Comment by LongDirtyAnimAlf** [comment]
@martok 
Ok. Now it becomes more clear.
I misunderstood your request/comment.
Please try the new commit.
ps: IMHO "git patch" must be "git apply"

**Comment by martok** [comment]
Oh of course, ´git apply´ is the correct one. With a minor change I got this working, however, I have found an issue with git-apply itself (and I'm pretty sure this worked before I created this issue...). I'll have to investigate this and see what to do about it... when I'm done I'll create a pull request for my changes in either case.

**Comment by LongDirtyAnimAlf** [comment]
Then I will close this issue for now, and consider it solved.
You are welcome to re-open it when necessary !
