### ISSUE TITLE
Toolchain arm-linux-gnueabihf

### ISSUE THREAD

**Issue by mariuszekpl** [LongDirtyAnimAlf/Reiniero-fpcup#18]
`--ostarget="linux" --cputarget="arm" --fpcOPT="-dFPC_ARMHF" --crossOPT="-CpARMV7A -CfVFPV3 -OoFASTMATH -CaEABIHF" --only="FPCCleanOnly,FPCBuildOnly"
`
For Tegra2/Tegra3 I always use Toolchain arm-linux-gnueabihf 
but in your code "m_any_to_linuxarm.pas"
constructor Tany_linuxarm.Create
I see: " FBinUtilsPrefix:='arm-linux-;"

And always must create extra files from arm-linux-gnueabihf  -> arm-linux (copy or link) 

Exists any better way ?

**Comment by LongDirtyAnimAlf** [comment]
Could you please try the new commit.
I have added gnueabihf as a search target !
