### ISSUE TITLE
fpcbootstrap 3.0

### ISSUE THREAD

**Issue by shobits1** [LongDirtyAnimAlf/Reiniero-fpcup#19]
you can now download fpcbootstrap 3.0 directly from : [ftp://ftp.freepascal.org/pub/fpc/dist/3.0.0/bootstrap/i386-win32-ppc386.zip](ftp://ftp.freepascal.org/pub/fpc/dist/3.0.0/bootstrap/i386-win32-ppc386.zip) instead of doing the intermediate compiler and waste time.

**Comment by LongDirtyAnimAlf** [comment]
Included ! Thanks !
