### ISSUE TITLE
Crosscompiler for Linux x86_64 to Linux i386

### ISSUE THREAD

**Issue by Bergmann89** [LongDirtyAnimAlf/Reiniero-fpcup#2]
- when searching for library paths (especially /usr/lib/i386-linux-gnu) the result of the previous checks is overwritten. So the check will always fail if /usr/lib/i386-linux-gnu does not exist on the system (see m_any_to_linux386.pas line ~90)
- when building the cross compiler with make "-Xd -Fl path/to/cross/libs" is passed in OPT, so linking the cross compiler will fail, because it will need the libraries of the host system, not the target system
- "-Xd -Fl path/to/cross/libs" need to be added to fpc.cfg

**Comment by LongDirtyAnimAlf** [comment]
First of all: thanks for you feedback.
1: agreed.
2+3: not clear to me. so please state your system and your cross-compile target, so I can simulate and check.

**Comment by Bergmann89** [comment]
2+3 was my fault, sry. with a new installed system everything is fine. Thanks. BTW: nice project ;)

**Comment by LongDirtyAnimAlf** [comment]
Your welcome !
