### ISSUE TITLE
server down

### ISSUE THREAD

**Issue by joeparkerz** [LongDirtyAnimAlf/Reiniero-fpcup#20]
Address for bintools is down: svn2.freepascal.org

**Comment by jsebosik** [comment]
This seems to work [http://svn.freepascal.org/svn/fpcbuild/tags/release_3_0_0/install/binw32/](url)

**Comment by joeparkerz** [comment]
It works but fpcup uses svn2...

**Comment by LongDirtyAnimAlf** [comment]
I will change svn2 into svn !
Stay tuned.

**Comment by LongDirtyAnimAlf** [comment]
Done.
