### ISSUE TITLE
Skip CHM build

### ISSUE THREAD

**Issue by joeparkerz** [LongDirtyAnimAlf/Reiniero-fpcup#21]
Please add feature to skip CHM files build every time. Thanks.

**Comment by LongDirtyAnimAlf** [comment]
Have you tried this option:
--skip="'helpfpc,helplazarus"

**Comment by joeparkerz** [comment]
Hi, will try now and close if ok!

**Comment by joeparkerz** [comment]
Seems it causes some problems.

fpclazup: info: Execute: C:\development\lazarus\lazbuild.exe. Params: --quiet,--quiet,--pcp=c:\development\config_lazarus,C:\development\lazarus\ide\startlazarus.lpi

fpclazup: info: Lazarus: buildmodulecustom: lazbuild startlazarus returned error code 217
Details:
fpclazup: info: Error running fpcup. Technical details: error executing sequence USERIDE; line: 2, param: USERIDE
fpclazup: info: Error running fpcup. Technical details: error executing sequence DefaultWin32; line: 8, param: USERIDE
Fpclazup failed.
Please check log for details. Possible troubleshooting steps:
- run again with --verbose and check for make, lazbuild errors etc.
- if compiling Lazarus, make sure your lhelp is closed.
- try removing all intermediate files by running fpcup with the --clean option
