### ISSUE TITLE
how to specify which bootstrap compiler to use?

### ISSUE THREAD

**Issue by wkitty42** [LongDirtyAnimAlf/Reiniero-fpcup#23]
i have several bootstrap compiler versions in my bootstrap directory... how can i specify which one to use to build a specific fpc?

eg:
x86_64-linux-ppcx64-2.6.2
x86_64-linux-ppcx64-2.6.4
x86_64-linux-ppcx64-3.0.0

fpcup seems to be hardcoded to use x86_64-linux-ppcx64 with no way to override it... i'm trying to build fixes_3_0 and want to easily try switching between the above 3.0.0 and 2.6.4 compilers without having to copy them to the single hardcoded name...

perhaps this should be a feature request?

**Comment by LongDirtyAnimAlf** [comment]
Please try the following, because I do not think it is ok to add a option to choose a compiler.
AFAIK, if you name the compiler of your choice:
intermediate_ppcx64
fpcup will use it as bootstrapper !
Put the intermediate compiler in the fpc bootstrap directory.

**Comment by wkitty42** [comment]
i am/was mainly looking for a way to ensure that i don't, for example, try to build FPC 2.6.4 with FPC 3.0.0... in other words, FPC 2.6.4 must be built with FPC 2.6.2... FPC 3.0.0 must be built with FPC 2.6.4... FPC trunk must be built with (at this time) FPC 3.0.0...

**Comment by LongDirtyAnimAlf** [comment]
Thanks for your explanation.
However, I do not think that fpcup is the suitable tool for your goal.
It is mainly used / made for installing / updating the latest FPC / Lazarus.
The original author made no provisions for your use-case.

I showed you a work-around that could help you in your use-case !

**Comment by wkitty42** [comment]
somehow we're missing something... the use case is exactly what fpcup is all about... it doesn't pull the 2.6.2 bootstrap compiler for building 3.0.0, does it? it attempts to locate and pull the 2.6.4 bootstrap compiler, right... the real problem, as simple as it is, is that fpcup uses one name in the bootstrap directory for all of the bootstrap compilers when it really should place the version number in the name as well so that it can use intelligence to choose the right compiler for what is being built...

eg:
  x86_64-linux-ppcx64-2.6.2
  x86_64-linux-ppcx64-2.6.4
  x86_64-linux-ppcx64-3.0.0

that's really all i'm asking for if we can't specify the compiler to use, make the tool smarter so that it uses the proper compiler automatically :smile_cat:

**Comment by LongDirtyAnimAlf** [comment]
I have updated fpc(laz)up to (automagically) use the correct bootstrapper.

https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/commit/2eae2c36b383654b5b6e79aa411d3c168c8afcf8

Tests and feedback would be welcome.

**Comment by LongDirtyAnimAlf** [comment]
Closed: no feedback.
