### ISSUE TITLE
Win32/Win64 cross compilers do not work

### ISSUE THREAD

**Issue by oliverhbailey** [LongDirtyAnimAlf/Reiniero-fpcup#26]
Hi,
I installed bootstraped x86_64 using fplazup64.exe. Building and compiling 64 bit applications works just fine. When I attempt to build a Win32 application uing Win32 and i386 the 32 bit program crashes on startup, before reaching main. The instructions on adding a cross compiler do not seem consistent throughout the documentation or with the current batch files on building cross compilers. Are there any instructions on how to build a cross compiler that works and a working text example for the target. In the past I have successfully built Win64, Win32, DOS, and Linux cross applications and tools without all this hassle. All the documentation with any examples seem to be several years out of date. Is there any documentation that is current in how the process has changed.

**Comment by LongDirtyAnimAlf** [comment]
First, the official FPC way of getting 64bit windows apps, is by cross-compiling from a 32bit windows FPC.
See: http://www.freepascal.org/down/x86_64/win64-netherlands.var
So, to be honest, I have never tested this setup (win64->win32). I will, when time is available.

About the docs.
I do not (yet) know what documentation.
Are you talking about FPC documentation or fpc(laz)up documentation.

Could you explain in more detail what you mean with "without all this hassle" ?

**Comment by oliverhbailey** [comment]
Hi Don,
The page link you sent doesn't appear if you navigate from the home page,
which is what I tried before posting. I dont know if there are broken page
links or non-working links, but the page link you sent only shows up if I
take it from the response you sent.
I googled fpc and free pascal cross compiling and none of the pre-built
croos compilers came up even once.
Maybe confusion is a better word than hassle. I've used Free Pascal and
Lazarus pre 2.6.4. This time around (3.0.0 and 1.6.0) I was going to use
fpclazupd. Since I have svn installed, i dowloaded the svn tree for
fpclazupd. There are a number of windows exe programs based on x86_64-win64
and win32. My guess is that may not have been the best approach. Again, I
took that approach since I did not find the page on win 64 cross compiling
or the arm, and android cross compilers download.

Oliver

**Comment by oliverhbailey** [comment]
Hi Don,
Got it!

I forgot corss compiling to Windows 64 was from Windows 32. I kept trying t
go Win64->Win32. deleted the complete installation and ran the win32
version of fpclazupd and eveything worked as it should. Thanks Don for
reminding me that Win64 is derived from the Win32.

Thank you,
Oliver

**Comment by LongDirtyAnimAlf** [comment]
Your welcome !
