### ISSUE TITLE
fpcup compile FPC for win32

### ISSUE THREAD

**Issue by jsebosik** [LongDirtyAnimAlf/Reiniero-fpcup#27]
Hello,

today I've tried to recompile fpc and during compilation it throws following error:

Start  now 16:37:07
make[5]: Leaving directory `R:/devel/fpc/compiler'
make[4]: Leaving directory `R:/devel/fpc/compiler'
R:/devel/fpcbootstrap/rm.exe -f ppc3.exe
R:/devel/fpcbootstrap/mv.exe -f ppc386.exe ppc3.exe
make[3]: Leaving directory `R:/devel/fpc/compiler'
R:/devel/fpcbootstrap/make 'FPC=R:/devel/fpc/compiler/ppc3.exe' 'OLDFPC=R:/devel/fpc/compiler/ppc2.exe' next CYCLELEVEL=4
make[3]: Entering directory `R:/devel/fpc/compiler'
R:/devel/fpc/compiler/ppc2.exe and R:/devel/fpc/compiler/ppc3.exe are equal
R:/devel/fpcbootstrap/cp.exe -fp R:/devel/fpc/compiler/ppc3.exe ppc386.exe
make[3]: Leaving directory `R:/devel/fpc/compiler'
R:/devel/fpcbootstrap/cmp.exe -i218 ppc3.exe ppc386.exe
R:/devel/fpcbootstrap/make utils_all 'FPC=R:/devel/fpc/compiler/ppc386.exe'
make[3]: Entering directory `R:/devel/fpc/compiler'
R:/devel/fpcbootstrap/make -C utils all
make[4]: Entering directory `R:/devel/fpc/compiler/utils'
R:/devel/fpcbootstrap/gmkdir.exe -p units/i386-win32
R:/devel/fpc/compiler/ppc386.exe -Ur -Xs -O2 -n -Fu.. -FuR:/devel/fpc/rtl/units/i386-win32 -FE. -FUunits/i386-win32 -vi-n-h- -di386 -dRELEASE fpc.pp
R:/devel/fpcbootstrap/make ppu.ppu NOCPUDEF=1
make[5]: Entering directory `R:/devel/fpc/compiler/utils'
R:/devel/fpc/compiler/ppc386.exe -Ur -Xs -O2 -n -Fu.. -FuR:/devel/fpc/rtl/units/i386-win32 -FE. -FUunits/i386-win32 -vi-n-h- -dRELEASE ../ppu.pas -Fu../generic -dGENERIC_CPU -Fi..
make[5]: Leaving directory `R:/devel/fpc/compiler/utils'
R:/devel/fpcbootstrap/make ppufiles.exe NOCPUDEF=1
make[5]: Entering directory `R:/devel/fpc/compiler/utils'
R:/devel/fpc/compiler/ppc386.exe -Ur -Xs -O2 -n -Fu.. -FuR:/devel/fpc/rtl/units/i386-win32 -FE. -FUunits/i386-win32 -vi-n-h- -dRELEASE ppufiles.pp -Fu../generic -dGENERIC_CPU -Fi..
make[5]: Leaving directory `R:/devel/fpc/compiler/utils'
R:/devel/fpcbootstrap/make ppudump.exe NOCPUDEF=1
make[5]: Entering directory `R:/devel/fpc/compiler/utils'
R:/devel/fpc/compiler/ppc386.exe -Ur -Xs -O2 -n -Fu.. -FuR:/devel/fpc/rtl/units/i386-win32 -FE. -FUunits/i386-win32 -vi-n-h- -dRELEASE ppuutils/ppudump.pp -Fu../generic -dGENERIC_CPU -Fi..
make[5]: Leaving directory `R:/devel/fpc/compiler/utils'
R:/devel/fpcbootstrap/make ppumove.exe NOCPUDEF=1
make[5]: Entering directory `R:/devel/fpc/compiler/utils'
R:/devel/fpc/compiler/ppc386.exe -Ur -Xs -O2 -n -Fu.. -FuR:/devel/fpc/rtl/units/i386-win32 -FE. -FUunits/i386-win32 -vi-n-h- -dRELEASE ppumove.pp -Fu../generic -dGENERIC_CPU -Fi..
make[5]: Leaving directory `R:/devel/fpc/compiler/utils'
R:/devel/fpc/compiler/ppc386.exe -Ur -Xs -O2 -n -Fu.. -FuR:/devel/fpc/rtl/units/i386-win32 -FE. -FUunits/i386-win32 -vi-n-h- -di386 -dRELEASE mkarmins.pp
R:/devel/fpc/compiler/ppc386.exe -Ur -Xs -O2 -n -Fu.. -FuR:/devel/fpc/rtl/units/i386-win32 -FE. -FUunits/i386-win32 -vi-n-h- -di386 -dRELEASE mkx86ins.pp
make[4]: Leaving directory `R:/devel/fpc/compiler/utils'
make[3]: Leaving directory `R:/devel/fpc/compiler'
R:/devel/fpcbootstrap/make wpocycle
make[3]: Entering directory `R:/devel/fpc/compiler'
rm -f ppc386.exe
R:/devel/fpcbootstrap/make 'FPC=R:/devel/fpc/compiler/ppc3.exe' 'OPT=-vi-n-h- -di386 -dGDB -dBROWSERLOG -Fux86 -Sew -OWdevirtcalls,optvmts -FWR:/devel/fpc/compiler/pp1.wpo' compiler
make[4]: Entering directory `R:/devel/fpc/compiler'
make[4]: Nothing to be done for `compiler'.
make[4]: Leaving directory `R:/devel/fpc/compiler'
rm -f ppc386.exe
rm: ppc386.exe: Permission denied
make[3]: *** [wpocycle] Error 1
make[3]: Leaving directory `R:/devel/fpc/compiler'
make[2]: *** [cycle] Error 2
make[2]: Leaving directory `R:/devel/fpc/compiler'
make[1]: *** [compiler_cycle] Error 2
make[1]: Leaving directory `R:/devel/fpc'
make: *** [build-stamp.i386-win32] Error 2
make: Leaving directory `R:/devel/fpc'

fpcup: info: FPC: Running fpc make all install failed with exit code 2
Details:
fpcup: ERROR: Error running BuildModuleCustom for module FPC
fpcup: info: Error running fpcup. Technical details: error executing sequence fpc; line: 5, param: FPC
fpcup: info: Error running fpcup. Technical details: error executing sequence Only; line: 1, param: fpc
Fpcup failed.
Please check log for details. Possible troubleshooting steps:
- run again with --verbose and check for make, lazbuild errors etc.
- if compiling Lazarus, make sure your lhelp is closed.
- try removing all intermediate files by running fpcup with the --clean option
  and/or manually deleting all *.ppu/*.a/*.o followed by svn up
- if that does not work: use the --uninstall option to remove all files
  including your FPC and Lazarus directories
- remove the files in the bootstrap directory. fpcup will redownload if required.
fpcup: info: 2. 8. 2016 16:37:10: fpcup finished.

Here is a command that was used to compile FPC from fixes_3_0 branch:
`fpcup --fpcURL=http://svn.freepascal.org/svn/fpc/branches/fixes_3_0 --installdir="r:\devel" --only=fpc --verbose`

Is it something fpcup/fpc related?
I've been updating fpc compiler quiet often (maybe once a month) and I've never hit any bug with fpcup so far.

Jan

**Comment by jsebosik** [comment]
Definitely not a FPCup problem. Seems like a problem of OS Win7 SP1.

**Comment by mariuszmaximus** [comment]
I see "Permission denied" in your compile messages 

I try download current fpcup and run your command 

on my windows 10 64 bit all works OK 
**fpcup: info: 2016-08-03 11:27:11: fpcup finished.**

**Comment by jsebosik** [comment]
I`ve tried on another box with Win7 and everything works fine, then on the same box with Win10 everything works fine too. 
Everything points to some problem with this one Win7 :).

**Comment by mariuszekpl** [comment]
sometimes problem build  on windows is with PATH  ! 

Please create bat and before 
fpcup ..... 

ADD
set PATH=c:\windows\system32
and then add 
fpcup.....
pause 

this metod work for me
