### ISSUE TITLE
fpcuprpi not running on Raspberry 1

### ISSUE THREAD

**Issue by sledge1977** [LongDirtyAnimAlf/Reiniero-fpcup#3]
I tried to run the binary fpcuprpi on my Raspberry 1 but recieved following output:
An unhandled exception occurred at $00016700:
EAccessViolation: Access violation
  $00016700

The fpcuprpi2 produces the same output.
On my Raspberry 2 the fpcuprpi2 runs fine.

Jens

**Comment by LongDirtyAnimAlf** [comment]
My mistake ... wrong architecture ... will resolve soon (ARMV6) !
