### ISSUE TITLE
Failure pi3 jessie.

### ISSUE THREAD

**Issue by magorium** [LongDirtyAnimAlf/Reiniero-fpcup#30]
Tested latest (0.99, today) arm release of fpcupdeluxe on my pi3.

Selected for creation of fpc 3.02 for arm/linux only. The script fails with last parts reading:

```
/home/pi/fpcupdeluxe/fpc/rtl/units/arm-linux/cprt0.o: In function `_haltproc_eabi':
(.text+0x88): undefined reference to `_fini'
/home/pi/fpcupdeluxe/fpc/rtl/units/arm-linux/cprt0.o: In function `_haltproc_eabi':
(.text+0x90): undefined reference to `_init'
fpmake.pp(49) Error: Error while linking
fpmake.pp(49) Fatal: There were 1 errors compiling module, stopping
Fatal: Compilation aborted
Makefile:1671: recipe for target 'fpmake' failed
make[2]: *** [fpmake] Error 1
make[2]: Leaving directory '/home/pi/fpcupdeluxe/fpc/packages'
Makefile:2652: recipe for target 'packages_smart' failed
make[1]: *** [packages_smart] Error 2
make[1]: Leaving directory '/home/pi/fpcupdeluxe/fpc'
Makefile:2848: recipe for target 'build-stamp.arm-linux' failed
make: *** [build-stamp.arm-linux] Error 2
make: Leaving directory '/home/pi/fpcupdeluxe/fpc'

fpcupdeluxe: info: FPC: Running fpc make all install failed with exit code 512
Details: 
fpcupdeluxe: ERROR: Error running BuildModuleCustom for module FPC
fpcupdeluxe: info: Error running fpcup. Technical details: error executing sequence fpc; line: 5, param: FPC
fpcupdeluxe: info: Error running fpcup. Technical details: error executing sequence Only; line: 1, param: fpc


ERROR: Fpclazupdeluxe failed.
```
I am unable to tell at this point if this is due 3.02 sources itself or fpcup doing something out of the ordinary there. Full log available on request.

Kind regards,
Ron.

**Comment by LongDirtyAnimAlf** [comment]
I just ran fpcupdeluxe myself on a RPi3, and it ended (FPC 3.0.2) without errors.
So its not a 3.0.2 problem.

But this line "haltproc_eabi" seems to point towards a hardfloat/softfloat problem.
What distro are you running ?

**Comment by magorium** [comment]
See also topic: Jessie.

The install is pretty much empty when i ran fpcupdeluxe, as i needed to add a svn client manually (even though i seem to remember you having stated somewhere that it automatically should download so when not present).

**Comment by magorium** [comment]
Well,

Using (latest released) fpcup shed some light on things.

I am on a raspberry pi 3, HF kernel, and executed:
./fpcup_linux_armhf --cputarget=arm --ostarget=linux --fpcopt="-dARMHF -CpARMV6 -CfVFPV2"

And fpcup initiate the sequence default arm and tries to create a cross-compiler(!), which fails. Same as for fpcdeluxe.

It seems to me that the "default arm sequence" does not create and/or support creating a HF compiler.

No idea how you managed to do that but, my knowledge on fpcup is next to none.

Kind regards,
Ron.

**Comment by LongDirtyAnimAlf** [comment]
If you define a CPU or OS target, fpcup tries to install a cross-compiler.
Which is not what you want.

Just run
./fpcup_linux_armhf   --fpcURL="trunk" --lazURL="trunk" --fpcOPT="-dFPC_ARMHF" --crossOPT="-CpARMV6 -CfVFPV2 -CaEABIHF"

**Comment by magorium** [comment]
Ah, progress !

First of all apologies for the wrong define in my above example. Simple case of type-over-error.

Now that i have full logs, i understand why parameter crossopt needs to be defined :-)

Thank you for the help LDAA. Clearly a case of user error there so, apologies for that.

Please feel free to consider this issue/ticket as Lucky, mr. Shumway ;-)
