### ISSUE TITLE
FPCCrossWin32-64 doesn't copy the compiled units to units/x86_64-Win64

### ISSUE THREAD

**Issue by murnur19** [LongDirtyAnimAlf/Reiniero-fpcup#32]
The last fpcup seems doesn't copy the compiled units for cross compile to units directory. I mean to `fpc\units\x86_64-Win64`.
I monitor the folder activity, it does create `x86_64-Win64` compiled units on every packages and rtl. But after completed there is no `fpc\units\x86_64-Win64` folder and all compiled units is removed. It's causing lazarus to yield "Cannot find system used by ...".

I'm using the same options as before. I can't remember what version of fpcup I had before.

`F:\development\fpcup\fpcup-i386-win32.exe --fpcURL="trunk" --only="FPCCrossWin32-64" --crossOPT="-CX -O3 -g- -Xs -XX" --keeplocalchanges --installdir="F:\development" --verbose --noconfirm`

[FPCCrossWin32-64.txt](https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/files/691807/FPCCrossWin32-64.txt)
[TMP00007.tmp.txt](https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/files/691808/TMP00007.tmp.txt)

Compile using fpc makefile seems doesn't have any problem.
`make all crossinstall INSTALL_PREFIX="F:\development\fpc" OS_TARGET=win64 CPU_TARGET=x86_64 OPT="-CX -O3 -g- -Xs -XX"`

**Comment by LongDirtyAnimAlf** [comment]
Confirmed. Will look into it !

**Comment by LongDirtyAnimAlf** [comment]
Solved.
See: https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/tag/1.2.0b
Please test.

**Comment by murnur19** [comment]
Seems fixed now. Thank you very much.
