### ISSUE TITLE
fpc(laz)up fails to recognize existing SVN repository

### ISSUE THREAD

**Issue by martok** [LongDirtyAnimAlf/Reiniero-fpcup#33]
It appears that http://svn.freepascal.org now always gets rewritten to the https version (good!), either by the svn client or the server.
However, because of the literal comparision in [TSVNClient](https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/blob/master/svnclient.pas#L763), fpcup fails to recognize an exsiting SVN repository:

```
 [2017-05-02 12:35:40.407 Info] FPC URL:            http://svn.freepascal.org/svn/fpc/trunk/
...
fpclazup: info: Checking out/updating FPC sources...
Executing : C:\Dev\fpcup\fpcbootstrap\svn\bin\svn.exe "info" "C:\Dev\fpcup\fpc_3_1" (working dir: )
Path: fpc_3_1
Working Copy Root Path: C:\Dev\fpcup\fpc_3_1
URL: https://svn.freepascal.org/svn/fpc/trunk
...
fpclazup: info: ERROR: repository URL in local directory and remote repository don't match.
```

It would probably make sense to strip the protocol before comparision (or rather, introduce a function to do that and use it in similar cases)?

**Comment by LongDirtyAnimAlf** [comment]
Yes, that makes perfect sense !
Will implement.

**Comment by LongDirtyAnimAlf** [comment]
Done. Thanks for reporting.
https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/commit/8292794ed1a9383c689f82ea0b95956b9463d277

**Comment by LongDirtyAnimAlf** [comment]
And released !

**Comment by martok** [comment]
Confirmed working, thanks!
I now have another problem though, will open a new issue...
