### ISSUE TITLE
Make SVN "deep-cleaning" optional

### ISSUE THREAD

**Issue by martok** [LongDirtyAnimAlf/Reiniero-fpcup#34]
After the fix for #33 I updated from 0.9 to 1.2.0r and noticed that my build chain broke in a different place.

When updating the SVN repo, there are now two calls to cleanup:
```
svn.exe "cleanup" "--non-interactive" $repo
svn.exe "cleanup" "--non-interactive" "--remove-unversioned" "--remove-ignored" $repo
```
At least the second one however appears to be a bit too much: fpclazup/svn now deletes all build artifacts _incuding those that `make distclean` before has kept_ . What this means is that it is no longer possible to build multiple targets in the same working copy in a row and collect binaries and objects afterwards.

I'm not sure if an option (as suggested in the issue title) is the best solution, but I feel like there should be a way to support this use case?

**Comment by LongDirtyAnimAlf** [comment]
You were using a very old version of fpcupdeluxe.
The newer version separates (in different directories) the FPC binaries from the FPC source.
(see corresponding setting in setup+)
In that case, the SVN commands only act on the FPC source directory.
Would this solve your issue ?

**Comment by martok** [comment]
The separate InstallDir does solve/avoid the issue for FPC.

> You were using a very old version of fpcupdeluxe.
Yeah I know, however upgrading it always tends to break my snapshot build chain - as it did now, spent the last day getting it somewhere usable again. Now I just found out that apparently startlazarus only gets built from module useride and I have no idea why that ever worked? In any case, it must now always be built because of the SVN cleanup.

**Comment by LongDirtyAnimAlf** [comment]
I will remove:
`svn.exe "cleanup" "--non-interactive" "--remove-unversioned" "--remove-ignored"`
in the next release !
