### ISSUE TITLE
fpcup.ini: outdated repository link

### ISSUE THREAD

**Issue by galfar** [LongDirtyAnimAlf/Reiniero-fpcup#35]
In fpcup.ini there's outdated repository link for:
[FPCUPModule56]
; Vampyre imaging library

Current repos are these:
http://hg.code.sf.net/p/imaginglib/code
https://bitbucket.org/galfar/lib-imaging

**Comment by LongDirtyAnimAlf** [comment]
Thanks !
https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/commit/3fe78964dc86ed0723eefeedb6022a50378ab845
