### ISSUE TITLE
Patch directories are deleted during patching

### ISSUE THREAD

**Issue by martok** [LongDirtyAnimAlf/Reiniero-fpcup#39]
Short story: I just lost my entire patch collection and had to pick them back from disk backups and the bugtracker. Some are gone forever.

Long story: between 1.6.0k and 1.6.0n, patching was refactored into `TInstaller.PatchModule`. This also changed the semantics significantly. The `patchfpc` directory is now completely cleared out, some patches extracted from fpcup, and then whatever was unpacked gets applied. Any user patches supplied (from `--fpcpatch`) now obviously fail.
Same for the Lazarus equivalents.

Would be cool if such changes could be at least noted somewhere, instead of being buried in diffs.

How is one supposed to specify user patches now?

**Comment by LongDirtyAnimAlf** [comment]
I am sorry about this !
You can define patches for FPC and Lazarus in Setup+
Please let me know if this suits your needs.
Otherwise I will revert the changes !!

**Comment by martok** [comment]
No need to revert, I think.
The options in the GUI version under Setup+ are the same as the fpclazup --xxxpatch, right? In that case, as a user I just have to stay away from the patch directories fpcupdeluxe uses, and use my own storage locations?

**Comment by martok** [comment]
It does seem to work.
Closing as no change required!

Just as a suggestion, maybe commit messages could be a bit more explicit in the future about what changed? This change was from "Fixed openssl problem with FPC stable", which is clearly not all that happened.

**Comment by LongDirtyAnimAlf** [comment]
Will do.
The patchfpc and patchlazarus directories were always ment for internal, but visible use.
Sorry for the inconvenience.
