### ISSUE TITLE
Path separator inserted in the wrong place

### ISSUE THREAD

**Issue by chrdan** [LongDirtyAnimAlf/Reiniero-fpcup#42]
In installerhelp.pas line 239 and installerlazarus.pas line 1448 it should read
`       then SVNPath:=ExcludeTrailingPathDelimiter(FSVNDirectory)+PathSeparator;`
instead of
`       then SVNPath:=PathSeparator+ExcludeTrailingPathDelimiter(FSVNDirectory);`

Otherwise you get paths like
`[2020-10-11 16:38:38.233 Info] LazarusNativeInstaller (SetPath): External program path:  O:\OmniMix_IDE\fpc\bin\i386-win32;O:\OmniMix_IDE\fpc;O:\OmniMix_IDE\fpcbootstrap;;O:\OmniMix_IDE\fpcbootstrap\svn\binO:\OmniMix_IDE\lazarus`
`[2020-10-11 16:42:41.733 Error] LazarusNativeInstaller (BuildModuleCustom: UserIDE): make.exe returned exit status #2`

Thanks for your great work!

**Comment by LongDirtyAnimAlf** [comment]
Thanks. Done.
https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/commit/277cd713df0d26579f91256654accbf85284ec37
Among many other changes.
Will update binaries soon.
