### ISSUE TITLE
Instructions for installing cross-compilers

### ISSUE THREAD

**Issue by MFernstrom** [LongDirtyAnimAlf/Reiniero-fpcup#43]
I'm using this to install FPC/Laz on a non-gui Linux server (Jenkins build node) but would also like to install cross-compilers for Windows and macOS.

With the GUI installer it's as simple as specifying the target and installing, what are the commandline versions?

**Comment by LongDirtyAnimAlf** [comment]
Have a look here:
https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/tree/master/scripts/windows

Its as simple as:
fpcup.exe --ostarget="android" --cputarget="arm" --only="FPCCleanOnly,FPCBuildOnly"
