### ISSUE TITLE
Freepascal SVN repos seem to be down, and no Git version available

### ISSUE THREAD

**Issue by JordanL2** [LongDirtyAnimAlf/Reiniero-fpcup#45]
From what I can tell, Free Pascal switched from SVN to Git? And their SVN repos are unavailable now.

I see there is a version 2.0 for fpcupdeluxe which switches from SVN to Git, but I need an installer I can use on the command line in batch mode. Is a version of this tool coming that uses Git? Thanks in advance!

**Comment by JordanL2** [comment]
Never mind, doing some more reading I can see a git version is coming! :)

**Comment by LongDirtyAnimAlf** [comment]
That is correct !
