### ISSUE TITLE
Cross-compiler does not seem to work (FPCLazUp)

### ISSUE THREAD

**Issue by grahamegrieve** [LongDirtyAnimAlf/Reiniero-fpcup#49]
So I go to a fresh empty directory, and I run the commands

md tools

curl -L https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/v2.2.0b/fpclazup-x86_64-win64.exe --output tools\fpclazup.exe

tools\fpclazup --fpcVersion=trunk.gitlab --lazVersion=trunk.gitlab --installdir=tools --noconfirm --include=anchordocking,anchordockingdsgn,lazprojectgroups,laz.virtualtreeview_package,lazdebuggerfp,fpdebug

tools\fpclazup --ostarget="linux" --cputarget="x64_64" --only="FPCCleanOnly,FPCBuildOnly"  --installdir=. --noconfirm

And the cross-compiler install fails with an error:

fpclazup: ERROR: FPCCrossInstaller (BuildModule: FPC): R:\fsbuild\fpc\Makefile not found. Severe error. Should not happen. Aborting.
Fpclazup failed.

Full logs attached (both console output and fpc.log):
[fpcup.log](https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/files/7565544/fpcup.log)
[console.log](https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/files/7565546/console.log)

**Comment by LongDirtyAnimAlf** [comment]
There were some mistakes in your script.
* wrong module names
* different install directory

However.
Fpcup was in the process of being updated. So included are also some changes that go well together with your script.

So.
Please use the latest release.
And use the command line as below.
(you may change the install directory as long as they are the same)

`tools\fpclazup --fpcVersion=trunk.gitlab --lazVersion=trunk.gitlab --noconfirm --installdir=tools --include=anchordocking,lazprojectgroups,virtualtreeview,fpdebug`
`tools\fpclazup --ostarget="linux" --cputarget="x86_64" --only="FPCCleanOnly,FPCBuildOnly" --installdir=tools --noconfirm`

**Comment by grahamegrieve** [comment]
thanks. So I fixed the mistakes (though it's confusing - there's two different package lists). And I ran it again with 2.2.0e. it still failed - logs attached.
[fpcup.log](https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/files/7568339/fpcup.log)
[console.log](https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/files/7568340/console.log)

**Comment by LongDirtyAnimAlf** [comment]
Do you even look at the logs yourself ?
And try to add the correct cross-bins and cross-libs into your install ?

> fpclazup: ERROR: Failed to get crossbinutils
> fpclazup: ERROR: Failed to get crosslibrary
>

**Comment by grahamegrieve** [comment]
Well, I saw that but I don't know what it means. Should I do something?

**Comment by LongDirtyAnimAlf** [comment]
For sure you need to do "something".
If you want to cross-compile, you need the appropriate binary tools and system libraries.

https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/crosslibs_v1.3/CrossLibsLinuxx64.zip
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/wincrossbins_v1.0/WinCrossBinsLinuxx64.zip

(you might use fpcupdeluxe for a primary install and see how all gets organized)

![cross](https://user-images.githubusercontent.com/10783972/142581638-cc8d05a5-df2a-440c-be0b-3eb6e359e217.JPG)

**Comment by LongDirtyAnimAlf** [comment]
See the action script.
https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/blob/master/.github/workflows/tester.yml

**Comment by grahamegrieve** [comment]
hmm my apologies - I assumed that fpclazup would handle that, like fpcupdeluxe does. Perhaps the error message should say something like that? (save stupid people like me asking stupid questions in git issues). But while I'm here...

this bash script:

wget -q https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/v2.2.0c/fpclazup-aarch64-darwin -O tools/fpclazup
sudo codesign --force --deep --sign - tools/fpclazup
chmod +x tools/fpclazup
tools/fpclazup --noconfirm --fpcVersion=trunk.gitlab --lazVersion=trunk.gitlab --installdir=tools --include=anchordocking,lazprojectgroups,virtualtreeview,fpdebug
tools/fpclazup --ostarget="Darwin" --cputarget="x86_64" --only="FPCCleanOnly,FPCBuildOnly" --installdir=tools --noconfirm

leads to this error: 

/Users/grahame/work/tools/fpc/bin/aarch64-darwin/ppcx64 -Ur -dFPC_USE_LIBC -Px86_64 -Ur -Xs -O2 -n -Fi../inc -Fi../x86_64 -Fi../unix -Fi../bsd -Fi../bsd/x86_64 -Fi../darwin/x86_64 -FD/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin -FE. -FU/Users/grahame/work/tools/fpc/rtl/units/x86_64-darwin -Fl/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib -XR/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -vw-n-h-l-d-u-t-p-c- -ap -dx86_64 -dRELEASE -FD/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin -XR/Applications/Xcode.app/Contents/Developer/Platforms/macOSX.platform/Developer/SDKs/macOSX.sdk -Fl/Applications/Xcode.app/Contents/Developer/Platforms/macOSX.platform/Developer/SDKs/macOSX.sdk/usr/lib/ -Fl/Applications/Xcode.app/Contents/Developer/Platforms/macOSX.platform/Developer/SDKs/macOSX.sdk/usr/lib/system -WM10.8  -Us -Sg ../bsd/system.pp
make[1]: *** [darwin_all] Error 2
make: *** [rtl_all] Error 2
genmath.inc(898,7) Fatal: Internal error 2014051001
Fatal: Compilation aborted
fpclazup: ERROR: FPCCrossInstaller (BuildModuleCustom: FPC): Running cross compiler fpc /usr/bin/make for x86_64-darwin failed with an error code.
Fpclazup failed.

I scanned for anything suggesting I should do something, and didn't see anything?

**Comment by LongDirtyAnimAlf** [comment]
> I assumed that fpclazup would handle that, like fpcupdeluxe does.

Hmmm, I assumed that everybody out there knew that fpcup is the blunt install tool that needs careful use by experienced FPC and Lazarus command line adepts. I guess some more documentation and hints might be useful. Will take care of that.

The issue you experience is a very special one.
I am not able to solve due to the fact that I do not have an OSX arm64 machine.
However, a compiler error is something that must never happen.
You might file a FPC compiler bugger about this and hope for some love.

I will close this issue.
Thanks for your feedback.

**Comment by grahamegrieve** [comment]
thanks for all the help - it all installs great now. It would be super cool if the "fpclazup: ERROR: Failed to get crossbinutils" error not only said 'you need to install it yourself' but also said where to look, if that's possible

**Comment by LongDirtyAnimAlf** [comment]
I will try to implement the download info.

**Comment by LongDirtyAnimAlf** [comment]
Implemented.
The lastest release also has a new option: --autotools.
Will download correct tools if needed.
Use with care.
