### ISSUE TITLE
Bug in "ExportOnly" and "--getfullrepo"

### ISSUE THREAD

**Issue by mariuszekpl** [LongDirtyAnimAlf/Reiniero-fpcup#5]
I see you add new interesing option --getfullrepo 
and at new property TRepoClient.ExportOnly 

But you always set ExportOnly := TRUE in constructor TRepoClient.Create; 
But never set correct version from --getfullrepo
Please FIX this !

**Comment by LongDirtyAnimAlf** [comment]
Fixed. Thanks for reporting !
