### ISSUE TITLE
M1 Mac version missing from 2.2.0f release

### ISSUE THREAD

**Issue by grahamegrieve** [LongDirtyAnimAlf/Reiniero-fpcup#50]
The aarch64-darwin version of fpclazup isn't included in 2.2.0f release. 2.2.0e release has been removed. And trying the x86_64 release of fpclazup gives the following error:

(3104) Compiling ./carbon/carbonbars.pp
/Users/grahame/work/tools/lazarus/lcl/interfaces/./carbon/carbonbars.pp(16,2) Error: (2023) User defined: only 32 bit cpu is supported
(1002) Target OS: Darwin for x86_64
(3104) Compiling debuggerintf.pas
(3104) Compiling dbgintfbasetypes.pas
(3104) Compiling dbgintfdebuggerbase.pp
(3104) Compiling dbgintfmiscclasses.pas
(3104) Compiling dbgintfpseudoterminal.pas
(3104) Compiling dbgintfcommonstrings.pas
(3104) Compiling ./carbon/carbonprivate.pp
(3104) Compiling ./carbon/carbondef.pp
/Users/grahame/work/tools/lazarus/lcl/interfaces/./carbon/carbondef.pp(187,1) Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: /Users/grahame/work/tools/fpc/bin/x86_64-darwin/ppcx64 returned an error exitcode

Because it should be cocoa, not carbon. I don't know whether this is an error in fpclazup or the source, though I don't see an option to set a widget set for fpclazup?

**Comment by LongDirtyAnimAlf** [comment]
Please test.
https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/tag/v2.2.0g

**Comment by grahamegrieve** [comment]
Yep, that does the trick nicely - thank you
