### ISSUE TITLE
Installation failure on macos: missing 7zip

### ISSUE THREAD

**Issue by osvegn** [LongDirtyAnimAlf/Reiniero-fpcup#54]
On install, fpclazup try to download 7zip and put it in '/7Zip' if it's not found, but on macos it's not possible to create a folder at '/'. Can it be possible to move the install folder to a subdir ?

**Comment by LongDirtyAnimAlf** [comment]
This is a bugger.
I need to update the binaries.
Stay tuned.

**Comment by osvegn** [comment]
I found another error with fpc.
lazbuild try to find fpc in the PATH env variable, but isn't set.
On linux, it seems that fpclazup stores the path to the fpc executable but not on macos.
Is it right or I mad a mistake during installation ?

**Comment by LongDirtyAnimAlf** [comment]
Please test.
https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/tag/v2.2.0s

**Comment by osvegn** [comment]
It works, thanks
