### ISSUE TITLE
Needed to create /7Zip

### ISSUE THREAD

**Issue by grahamegrieve** [LongDirtyAnimAlf/Reiniero-fpcup#55]
I needed to create a directory 7Zip at the root of the filesystem in order to run FPCLazUp on Ubuntu 23 - immediately it started running it failed 

An unhandled exception occurred at $000000000418B1A:
EFCreateError: Unable to create file "/7Zip/7zz": No such file or directory
  $..418B1A
  $..418933
  $..47453C

Vanilla Ubuntu 23. Commands:

echo "Get fpclazup"

mkdir tools

wget -q https://github.com/LongDirtyAnimAlf/Reiniero-fpcup/releases/download/v2.2.0q/fpclazup-x86_64-linux -O tools/fpclazup

chmod +x tools/fpclazup

echo "Build Lazarus"

tools/fpclazup --noconfirm --fpcVersion=stable.gitlab --lazVersion=stable.gitlab --installdir=tools

**Comment by grahamegrieve** [comment]
if I create the /7Zip directory and make it buildable, it'll work

**Comment by LongDirtyAnimAlf** [comment]
Yes, this is a bugger.
Please use the latest release that solves this issue.

**Comment by grahamegrieve** [comment]
thanks
