### ISSUE TITLE
FPC trunk cannot compile with old make 3.82 bug.

### ISSUE THREAD

**Issue by rasberryrabbit** [LongDirtyAnimAlf/Reiniero-fpcup#56]
There is problem with FPC trunk.  
Old make 3.82's bug make error when compiling win32 target.
  
Bug patched [make-3.82-pololu2](https://github.com/pololu/make) works ok with compiling undefined "FPC_DOTTEDUNITS".  
But compiling defined "FPC_DOTTEDUNITS" still fails.  
  
Please include this  [make-3.82-pololu2](https://github.com/pololu/make) with fpc(laz)up windows binutils.

**Comment by LongDirtyAnimAlf** [comment]
As FPC trunk is under very heavy changes, I will not yet review this issue.
The whole FPC build system is changing at the moment.
Please wait for things to be a bit more stable.

**Comment by rasberryrabbit** [comment]
Ok, I will wait for more stable.
