### ISSUE TITLE
Pos() function with 3 parameters 

### ISSUE THREAD

**Issue by mariuszekpl** [LongDirtyAnimAlf/Reiniero-fpcup#6]
In m_any_to_androidarm.pas 
I found two places
ndkversion:=Pos(DirectorySeparator,FBinUtilsPath,ndkversion); 

But my FPC has only two parameters 
http://www.freepascal.org/docs-html/rtl/system/pos.html

Could you change to 
ndkversion:=Pos(DirectorySeparator,FBinUtilsPath);

**Comment by LongDirtyAnimAlf** [comment]
On my system, Pos can have 2 or 3 arguments.
But then again, changed Pos to PosEx.

**Comment by mariuszekpl** [comment]
Thanks for favorable consideration my request.
But I have to ask: What version fpc/lazarus has pos() with 3 arguments.

**Comment by LongDirtyAnimAlf** [comment]
I have fpc 3.1.1 (trunk with new RTTI)

Inside \fpc\rtl\inc\systemh.inc, I have:

function  pos(const substr : shortstring;c:char; Offset: Sizeint = 1): SizeInt;
Function  Pos (const Substr : RawByteString; const Source : RawByteString; Offset: Sizeint = 1) : SizeInt;
Function  Pos (c : AnsiChar; const s : RawByteString; Offset: Sizeint = 1) : SizeInt;

**Comment by mariuszekpl** [comment]
I have 3.1.1 but too old ;) 
31464 revison michael  2015-08-31 15:05:37 * Add offset to Pos functions, Delphi XE 8 compatible.
Thx
