### ISSUE TITLE
Have 3 problems on ReactOS 0.4 RC1

### ISSUE THREAD

**Issue by pbreneman** [LongDirtyAnimAlf/Reiniero-fpcup#8]
They are documented here:
http://wiki.freepascal.org/Small_Virtual_Machines#ReactOS_virtual_machine

**Comment by pbreneman** [comment]
Actually only the first problem (exception in fpcup) is maybe a fpcup problem...

**Comment by pbreneman** [comment]
I tried on a minimal VMware XP VM and everything works OK!  So the first two problems seem to be caused by ReactOS 0.4.0 RC1.  I should have checked XP before coming here.  Sorry!

**Comment by LongDirtyAnimAlf** [comment]
Thanks for your feedback !
