### ISSUE TITLE
make and parameter "--jobs="

### ISSUE THREAD

**Issue by mariuszekpl** [LongDirtyAnimAlf/Reiniero-fpcup#9]
New interesting error! ;)

When fpcup run make it add extra parameter  make** "--jobs=12"** ....

It is problem for trunk fpc or it is problem for my system :) 
Few days ago I update Debian 8.1 -> 8.3 (now I have GNU Make 4.0)

If I run make 

> make "FPC=/home/max/lazarus/3.0.0/x86_64-linux-ppcx64" "--directory=/homemax/lazarus20151229/fpc" "OVERRIDEVERSIONCHECK=1" OPT=-g -gl -O1  "all"

All works OK !

If run 

> make --jobs=12 "FPC=/home/max/lazarus/3.0.0/x86_64-linux-ppcx64" "--directory=/homemax/lazarus20151229/fpc" "OVERRIDEVERSIONCHECK=1" OPT=-g -gl -O1  "all"

I have error

> Fatal: Can't find unit objpas used by exeinfo

Could you add parameter to fpcup to disable paraller make ?

**Comment by LongDirtyAnimAlf** [comment]
--NoJobs.

Please test !

**Comment by mariuszekpl** [comment]
Thx  
parameter name is --disablejobs
